version: "3.3"

services:
  
  redis:
    image: "redis:alpine"
    command: --port ${REDIS_PORT}

  gateway:
    env_file: config.env
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    ports: 
      - "${HOST_CONTROLLER_PORT}:${CONTROLLER_PORT}" 

  webhooks:
    env_file: config.env
    build:
      context: .
      dockerfile: src/webhooks/Dockerfile